### ISSUE TITLE
Pygwy console

### ISSUE THREAD

**Issue by jbuencuerpo** [flathub/net.gwyddion.Gwyddion#17]
I can't find the python console. Is this package built without that option?
Thanks,

**Comment by Hofer-Julian** [comment]
It is at least not disabled.
https://github.com/flathub/net.gwyddion.Gwyddion/blob/a737b6c73b27b6be082c6d4d4777d6560c54ddac/net.gwyddion.Gwyddion.json#L67

What do I need to do to enable it?

**Comment by jbuencuerpo** [comment]
Hi,
I have looked into how to compile it. You need to pass the --with-python flag, but it relies on python2-dev, python-gobject2 and pytgk2. 

I have successfully compiled it locally using the '--with-python' flag , old-school (sorry I am not familiar with flatpak, yet)

```
./configure --with-python --prefix=/opt/gwyddion-dev
make
make install
```

To make pygwy work you need python2-dev, an python-gobject2, luckily is on my  distro (Pop-os 20.04) for now..

```
apt show python-gobject-2-dev
Package: python-gobject-2-dev
Version: 2.28.6-14ubuntu1
Priority: optional
Section: universe/oldlibs
Source: pygobject-2
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Josselin Mouette <joss@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 2,371 kB
Depends: libffi-dev (>= 3.0.5), libglib2.0-dev (>= 2.24.0), python2-dev, python-gobject-2 (>= 2.28.6-14ubuntu1), python2:any
Recommends: docbook-xsl
Breaks: python-gobject-dev (<< 2.90)
Replaces: python-gobject-dev (<< 2.90)
Download-Size: 193 kB
APT-Manual-Installed: yes
APT-Sources: http://us.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
Description: development headers for the static GObject Python bindings
 GObject is an abstraction layer that allows programming with an object
 paradigm that is compatible with many languages. It is a part of Glib,
 the core library used to build GTK+ and GNOME.
 .
 This package contains the development headers needed to build
 static Python bindings relying on pygobject. Note that this is obsolete, new
 libraries and applications should use the dynamic gobject-introspection
 bindings (which are provided by the python-gi package).
``` 

 But I think the problematic one is pygtk2. I was able to install it using [2], that's an old package, at least on deb based distros.
https://askubuntu.com/questions/1235271/pygtk-not-available-on-focal-fossa-20-04

```
Package: python-gtk2
Version: 2.24.0-5.1ubuntu2
Status: install ok installed
Priority: optional
Section: python
Source: pygtk
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Sebastien Bacher <seb128@debian.org>
Installed-Size: 3,429 kB
Depends: python (<< 2.8), python (>= 2.7), python:any (>= 2.6.6-7~), libatk1.0-0 (>= 1.12.4), libc6 (>= 2.14), libcairo2 (>= 1.2.4), libgdk-pixbuf2.0-0 (>= 2.22.0), libglib2.0-0 (>= 2.24.0), libgtk2.0-0 (>= 2.24.0), libpango-1.0-0 (>= 1.22.0), libpangocairo-1.0-0 (>= 1.21.4), python-cairo (>= 1.0.2-1.1), python-gobject-2 (>= 2.21.3)
Suggests: python-gtk2-doc
Breaks: python-gtkglext1 (<< 1.1.0-7~)
Homepage: http://www.pygtk.org/
Download-Size: unknown
APT-Manual-Installed: yes
APT-Sources: /var/lib/dpkg/status
Description: Python bindings for the GTK+ widget set
 This archive contains modules that allow you to use GTK+ in Python
 programs.
 .
 This package is deprecated, you should migrate to using
 gobject-introspection (GIR) based python bindings instead (PyGObject).
 https://wiki.gnome.org/Projects/PyGObject/IntrospectionPorting
 
 
```
Is it possible to do on flatpak something similar? like using these two old packages? 

I think the rpm package has python support, but not sure. 

Thank you in any case,

References:
[1] http://gwyddion.net/documentation/user-guide-en/installation-dependencies.html
[2] https://sourceforge.net/p/gwyddion/discussion/pygwy/thread/24a071efea/
[3] https://askubuntu.com/questions/1235271/pygtk-not-available-on-focal-fossa-20-04

**Comment by Hofer-Julian** [comment]
Yeah, that should be possible, but it would be a bit of work. All necessary packages would need to be compiled from scratch. 

If you want to tackle this, I can help you, but I probably won't do it myself 😊

**Comment by jbuencuerpo** [comment]
Ok, it's a pity, because t it is a very good tool for scientists, but I  understand this program is very niche and if you are not using it is not big deal.

Can you point me in the right direction? Like a good source to: 

1) Learn to translate the make commands to flatpak. 
2) How to add dependencies to build them together?

I cannot promise I will do it soon, (maybe summer?), but at least I will look into it. I may add a tutorial like on a gist or something similar, so in the meantime other people can use it.
Thanks,

**Comment by Hofer-Julian** [comment]
I felt like doing it and I think it should be enabled now.

You can try it here https://github.com/flathub/net.gwyddion.Gwyddion/pull/22
Enjoy!

**Comment by jbuencuerpo** [comment]
It works! Thank you so much.

**Comment by Hofer-Julian** [comment]
Glad to hear that, I'll merge it then.

Always happy to help nice people who actively help to find a solution 😊
