### ISSUE TITLE
Problem opening POIR and vtk4 files

### ISSUE THREAD

**Issue by jbuencuerpo** [flathub/net.gwyddion.Gwyddion#34]
Hello,
I have been having trouble opening .poir and vtk files. With the .deb installed from the ppa there is no problem. 

The poir format is compressed, if I decompressed (unzipped?) the file, I can open normally with gwyddion from flatpak each subfile. I suspect the problem is that the flatpak is released without zip support? There was something similar in 2019 version 
 
"2019-09-22: Version 2.54 was, unfortunately, relased without ZIP support, meaning that a bunch of file formats cannot be loaded: APE DAX, OpenGPS, JPK force data, NanoObserver, NanoScanTech, Olympus POIR, Sensofar PLUx and SPMx. This affects not just MS Windows executables, but ZIP support is silently disabled also when you compile from source code. We will be releasing 2.55 in several weeks with a fix. Please use version 2.53 or development snapshots meanwhile if you need to read some of the affected file formats."

[http://gwyddion.net/](http://gwyddion.net/)

Best regards and thank you for supporting this niche (but extremely valuable) program.
Jerónimo

**Comment by Hofer-Julian** [comment]
As far as I can tell gwyddion should have zip support per default, the flatpak doesn't disable that.
I wouldn't know how to fix this, but I am happy to review pull requests.

**Comment by jbuencuerpo** [comment]
Hello, 
yes, I think is a problem in upstream with the spcfile module, is different from the .deb and the flatpak (is newer the flatpak one). I will report upstream,
Thanks
