### ISSUE TITLE
GtkGLExt module

### ISSUE THREAD

**Issue by filipestevao** [flathub/net.gwyddion.Gwyddion#6]
Hi,
I noticed that the GtkGLExt module was dropped in commit [c3f9542](https://github.com/flathub/net.gwyddion.Gwyddion/commit/c3f9542fd527a1ee66e7252d8e41988d0d965db0) and this is a [build dependency](http://gwyddion.net/documentation/user-guide-en/installation-dependencies.html) for OpenGL 3D data views.
Is there any chance to return with the module?
Thanks.

**Comment by Hofer-Julian** [comment]
I experimented with https://github.com/flathub/net.gwyddion.Gwyddion/pull/7 and I remember now why I originally removed it.
I couldn't get it to compile with an updated runtime. If you want to try your luck, I'd be happy to merge a pull request

**Comment by filipestevao** [comment]
Build #8 successful.

A simple patch from [aur.archlinux.org](https://aur.archlinux.org/cgit/aur.git/tree/0002-disable-shaper.patch?h=pangox-compat) solved the problem.

**Comment by Hofer-Julian** [comment]
Nice! Thanks a lot!
It is probably okay that a GTK2 app requires a few patches to work 😅
